package com.frontend.kori;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.server.Page;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.navigator.Navigator;
import com.frontend.kori.NavigatorUI;


public class Content extends CustomComponent implements View {
	
	Navigator navigator;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button logout;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Content() {
		Page.getCurrent().setTitle("Ostoskori - Riskin raksukori!");
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		/*
		 * napin painalluksella logout ja takaisin login ruutuun
		 */
		logout.addListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				// TODO niittaa logout funktio backendista
				logout();
				navigator.navigateTo(NavigatorUI.LOGIN);
			}
		}); 
		
		
	} 

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// logout
		logout = new Button();
		logout.setCaption("Logout");
		logout.setImmediate(true);
		logout.setWidth("-1px");
		logout.setHeight("-1px");
		mainLayout.addComponent(logout, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO mika taa on hei?
		
	}

}
