package com.frontend.kori;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.Page;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.server.Page;
import com.vaadin.navigator.Navigator;
import com.frontend.kori.NavigatorUI;

public class Login extends CustomComponent implements View {
	
	Navigator navigator;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button login;
	@AutoGenerated
	private PasswordField password;
	@AutoGenerated
	private TextField name;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Login() {
		Page.getCurrent().setTitle("Login - Ostoskori");
		buildMainLayout();
		setCompositionRoot(mainLayout);
		login.addListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				login();
				navigator.navigateTo(NavigatorUI.CONTENT);
				// TODO Auto-generated method stub
				
			}
		});

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1,
				"bottom:619.0px;left:100.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("116px");
		verticalLayout_1.setMargin(false);
		verticalLayout_1.setSpacing(true);
		
		// name
		name = new TextField();
		name.setCaption("Nimi");
		name.setImmediate(false);
		name.setWidth("-1px");
		name.setHeight("-1px");
		verticalLayout_1.addComponent(name);
		
		// password
		password = new PasswordField();
		password.setCaption("Salasana");
		password.setImmediate(false);
		password.setWidth("-1px");
		password.setHeight("-1px");
		verticalLayout_1.addComponent(password);
		
		// login
		login = new Button();
		login.setCaption("Login");
		login.setImmediate(true);
		login.setWidth("-1px");
		login.setHeight("-1px");
		verticalLayout_1.addComponent(login);
		verticalLayout_1.setComponentAlignment(login, new Alignment(24));
		
		return verticalLayout_1;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO mita talla tehdaan?
		
	}

}
