package com.frontend.kori;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.LoginForm;

public class Login extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button bcreateuser;
	@AutoGenerated
	private Label otsikko;
	@AutoGenerated
	private LoginForm loginform;
	@AutoGenerated
	private Button linkki;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Login() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1024px");
		mainLayout.setHeight("768px");
		
		// top-level component properties
		setWidth("1024px");
		setHeight("768px");
		
		// linkki
		linkki = new Button();
		linkki.setCaption("Asteriski.fi");
		linkki.setImmediate(true);
		linkki.setWidth("-1px");
		linkki.setHeight("-1px");
		mainLayout.addComponent(linkki, "top:20.0px;left:20.0px;");
		
		// loginform
		loginform = new LoginForm();
		loginform.setStyleName("v-loginform");
		loginform.setImmediate(false);
		loginform.setWidth("-1px");
		loginform.setHeight("-1px");
		mainLayout.addComponent(loginform, "top:160.0px;left:300.0px;");
		
		// otsikko
		otsikko = new Label();
		otsikko.setImmediate(false);
		otsikko.setWidth("-1px");
		otsikko.setHeight("-1px");
		otsikko.setValue("Asteriskin raksukori");
		mainLayout.addComponent(otsikko, "top:102.0px;left:323.0px;");
		
		// bcreateuser
		bcreateuser = new Button();
		bcreateuser.setCaption("Luo uusi kayttaja");
		bcreateuser.setImmediate(true);
		bcreateuser.setWidth("-1px");
		bcreateuser.setHeight("-1px");
		mainLayout.addComponent(bcreateuser, "top:280.0px;left:300.0px;");
		
		return mainLayout;
	}

}
