package com.frontend.kori;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;

public class Luettelo extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label csaldo;
	@AutoGenerated
	private Table hinnasto;
	@AutoGenerated
	private Link lasteriski;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private TextField tsumma;
	@AutoGenerated
	private Button blogout;
	@AutoGenerated
	private Button bhyvaksy;
	@AutoGenerated
	private Button btalleta;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Luettelo() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1024px");
		mainLayout.setHeight("768px");
		
		// top-level component properties
		setWidth("1024px");
		setHeight("768px");
		
		// btalleta
		btalleta = new Button();
		btalleta.setCaption("Talleta rahaa");
		btalleta.setImmediate(true);
		btalleta.setWidth("-1px");
		btalleta.setHeight("-1px");
		mainLayout.addComponent(btalleta, "top:400.0px;left:380.0px;");
		
		// bhyvaksy
		bhyvaksy = new Button();
		bhyvaksy.setCaption("Hyvaksy ostokset");
		bhyvaksy.setImmediate(true);
		bhyvaksy.setWidth("-1px");
		bhyvaksy.setHeight("-1px");
		mainLayout.addComponent(bhyvaksy, "top:440.0px;left:380.0px;");
		
		// blogout
		blogout = new Button();
		blogout.setCaption("Kirjaudu ulos");
		blogout.setImmediate(true);
		blogout.setWidth("-1px");
		blogout.setHeight("-1px");
		mainLayout.addComponent(blogout, "top:14.0px;left:20.0px;");
		
		// tsumma
		tsumma = new TextField();
		tsumma.setImmediate(false);
		tsumma.setWidth("-1px");
		tsumma.setHeight("-1px");
		mainLayout.addComponent(tsumma, "top:440.0px;left:200.0px;");
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		mainLayout.addComponent(textField_2, "top:400.0px;left:200.0px;");
		
		// lasteriski
		lasteriski = new Link();
		lasteriski.setCaption("Asteriski.fi");
		lasteriski.setImmediate(false);
		lasteriski.setWidth("-1px");
		lasteriski.setHeight("-1px");
		mainLayout.addComponent(lasteriski, "top:26.0px;left:699.0px;");
		
		// hinnasto
		hinnasto = new Table();
		hinnasto.setCaption("Hyveisten hinnat");
		hinnasto.setImmediate(false);
		hinnasto.setWidth("500px");
		hinnasto.setHeight("-1px");
		mainLayout.addComponent(hinnasto, "top:60.0px;left:160.0px;");
		
		// csaldo
		csaldo = new Label();
		csaldo.setImmediate(false);
		csaldo.setWidth("-1px");
		csaldo.setHeight("-1px");
		csaldo.setValue("Ostokset yhteensa");
		mainLayout.addComponent(csaldo, "top:440.0px;left:80.0px;");
		
		return mainLayout;
	}

}
